### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by liartist** [mandiant/flare-fakenet-ng#128]
As I tried to execute fakenet.exe or fakenet.py,
`UnicodeEncodeError: 'ascii' codec can't encode characters in position 33-34: ordinal not in range(128)`
error came out.
I think it's about unicode and ASCII encoding error.
Since it's not about single source code, I couldn't use 'encoding:utf-8' method.

Here's my environment
VirtualBox 6.0.8
Windows 7 32bit
Python 2.7.16
I installed every requirements fakenet needs, so that would not be a problem.

**Comment by htnhan** [comment]
@liartist  Thank you for using and supporting Fakenet-NG. Do you mind providing the complete stack trace to help us figure out where things fail?

Thanks,

**Comment by liartist** [comment]
Thank you for the fast support!
I tried 2 versions of fakenet, the standalone (1.4.3) and python build (1.4.9) version.
Here's 2 stack traces.

fakenet 1.4.3
`C:\Users\Administrator\Desktop\fakenet1.4.3>fakenet.exe

  ______      _  ________ _   _ ______ _______     _   _  _____
 |  ____/\   | |/ /  ____| \ | |  ____|__   __|   | \ | |/ ____|
 | |__ /  \  | ' /| |__  |  \| | |__     | |______|  \| | |  __
 |  __/ /\ \ |  < |  __| | . ` |  __|    | |______| . ` | | |_ |
 | | / ____ \| . \| |____| |\  | |____   | |      | |\  | |__| |
 |_|/_/    \_\_|\_\______|_| \_|______|  |_|      |_| \_|\_____|

                        Version 1.4.3
  _____________________________________________________________
                   Developed by FLARE Team
  _____________________________________________________________

06/06/19 01:54:47 PM [           FakeNet] Loaded configuration file: configs\def
ault.ini
06/06/19 01:54:48 PM [          Diverter] Capturing traffic to packets_20190606_
135448.pcap
06/06/19 01:54:48 PM [          Diverter] Using default listener proxytcplistene
r on port 38926
06/06/19 01:54:48 PM [          Diverter] Using default listener proxyudplistene
r on port 38926
06/06/19 01:54:48 PM [          Diverter] WARNING: No gateways configured!
Traceback (most recent call last):
  File "fakenet\fakenet.py", line 380, in <module>
  File "fakenet\fakenet.py", line 355, in main
  File "fakenet\fakenet.py", line 156, in start
  File "fakenet\diverters\windows.py", line 97, in __init__
  File "fakenet\diverters\diverterbase.py", line 615, in __init__
  File "fakenet\diverters\winutil.py", line 381, in fix_gateway
  File "subprocess.py", line 185, in check_call
  File "subprocess.py", line 172, in call
  File "subprocess.py", line 394, in __init__
  File "subprocess.py", line 614, in _execute_child
UnicodeEncodeError: 'ascii' codec can't encode characters in position 37-38: ord
inal not in range(128)
[2444] Failed to execute script fakenet

C:\Users\Administrator\Desktop\fakenet1.4.3>`

fakenet 1.4.9
`C:\Users\Administrator\Desktop\flare-fakenet-ng-master\fakenet>python fakenet.py


  ______      _  ________ _   _ ______ _______     _   _  _____
 |  ____/\   | |/ /  ____| \ | |  ____|__   __|   | \ | |/ ____|
 | |__ /  \  | ' /| |__  |  \| | |__     | |______|  \| | |  __
 |  __/ /\ \ |  < |  __| | . ` |  __|    | |______| . ` | | |_ |
 | | / ____ \| . \| |____| |\  | |____   | |      | |\  | |__| |
 |_|/_/    \_\_|\_\______|_| \_|______|  |_|      |_| \_|\_____|

                        Version 1.4.9
  _____________________________________________________________
                   Developed by FLARE Team
  _____________________________________________________________

06/06/19 01:57:02 PM [           FakeNet] Loaded configuration file: configs\def
ault.ini
06/06/19 01:57:03 PM [          Diverter] Capturing traffic to packets_20190606_
135703.pcap
06/06/19 01:57:03 PM [          Diverter] WARNING: No gateways configured!
Traceback (most recent call last):
  File "fakenet.py", line 437, in <module>
    main()
  File "fakenet.py", line 412, in main
    fakenet.start()
  File "fakenet.py", line 168, in start
    self.diverter = Diverter(self.diverter_config, self.listeners_config, ip_add
rs, self.logging_level)
  File "C:\Users\Administrator\Desktop\flare-fakenet-ng-master\fakenet\diverters
\windows.py", line 97, in __init__
    ip_addrs, logging_level)
  File "C:\Users\Administrator\Desktop\flare-fakenet-ng-master\fakenet\diverters
\diverterbase.py", line 644, in __init__
    gw_ok = self.fix_gateway()
  File "C:\Users\Administrator\Desktop\flare-fakenet-ng-master\fakenet\diverters
\winutil.py", line 381, in fix_gateway
    stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python27\lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 614, in _execute_child
    args = '{} /c "{}"'.format (comspec, args)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 37-38: ord
inal not in range(128)

C:\Users\Administrator\Desktop\flare-fakenet-ng-master\fakenet>`

Thank you!

**Comment by mah-nyan** [comment]
This error is cause by Character code.
Maby, your ethernet adapter is not English.
I used Japanese name and same Error.But I changed "Ethernet0" taht was no error. 
![fakenet](https://user-images.githubusercontent.com/48166727/80429977-4a82ba80-8928-11ea-8367-11eb4e9f0c9c.jpg)

**Comment by samrath-sudesh-acharya** [comment]
@tinajn I don't think this problem exists anymore as every adapter name is of the type `LPWSTR` ( It is a pointer to a null-terminated string of 16-bit Unicode characters) 

```python
   IP_ADAPTER_ADDRESSES._fields_ = [
   ...
   ("FriendlyName",  LPWSTR),
   ...
  ]
```

Some Examples:

![image](https://user-images.githubusercontent.com/76547134/227784537-ce9cade4-9402-443a-9e99-8e9c2a4bbbfe.png)
![image](https://user-images.githubusercontent.com/76547134/227784591-e1ba470a-7791-4ff7-95d1-e255520e9ae4.png)

**Comment by tinajn** [comment]
@samrath-sudesh-acharya Thanks for testing this out! I have tested on my end and it appears to have been an issue with the way ```subprocess.check_call()``` handled non-ASCII characters in Python 2. 

As @samrath-sudesh-acharya mentioned this issue is not observed anymore as we have ported to Python 3. @liartist could you confirm?

**Comment by tinajn** [comment]
Closing this issue.
