### ISSUE TITLE
Broken internet and DNS error after starting Fakenet

### ISSUE THREAD

**Issue by mgray5** [mandiant/flare-fakenet-ng#150]
After starting fakenet, my internet in my Windows 7 VM went out with an error stating that there was a DNS error. I restarted my home router, but that's not working.  I tried to use a work around from another post with a command netsh interface ip set dns name="Ethernet" dhcp, but that didn't work. Any ideas will be greatly appreciated.

**Comment by williballenthin** [comment]
This is expected behavior. Fakenet will reconfigure DNS settings and intercept most/all traffic from the running host. You should run fakenet in dedicated virtual machines, likely in "Host-Only" mode, for analysis.

**Comment by nikkoxgonzales** [comment]
this killed my pc internet anyway to reverse it?
