### ISSUE TITLE
Ignoring IP / Port

### ISSUE THREAD

**Issue by dindibo** [mandiant/flare-fakenet-ng#151]
I'm trying to run FakeNet on my analysis VM,
it works fine but I can't use mstsc (RDP) while running FakeNet because it immediately hooks the connection.

Is it possible to change something in the configuration to ignore some IPs or ports so that it won't hook those conversations?

**Comment by mr-tz** [comment]
You can exclude processes and connections via the configuration. See https://www.mandiant.com/resources/improving-dynamic-malware-analysis-with-cheat-codes-for-fakenet-ng for more details.

**Comment by dindibo** [comment]
Thanks a lot!
