### ISSUE TITLE
Test scripts to Python 3

### ISSUE THREAD

**Issue by strictlymike** [mandiant/flare-fakenet-ng#152]
Migrate FakeNet-NG automated test script (`test.py`) to Python 3.

Privately take note of any migration discoveries relevant to modules that may be used by FakeNet-NG itself, including but not limited to the following modules:
* `netifaces`
* `ConfigParser`

Use the test script for both Windows and Linux testing, to confirm that the results using Python 3 match the results using Python 2.

Before releasing, verify that the setup requirements for the Python 3 version of `test.py` are well-understood and are documented in a `requirements.txt` file (and/or in accompanying documentation).

**Comment by tina-johnson1** [comment]
Working on this issue.
