### ISSUE TITLE
Bug in ProxyListener.py

### ISSUE THREAD

**Issue by tinajn** [mandiant/flare-fakenet-ng#161]
Error:
```
Exception in thread Thread-4057:
Traceback (most recent call last):
  File "listeners\ProxyListener.py", line 131, in run
NameError: name 'exit' is not defined
```
Fix:
`exit(1)` at [L131](https://github.com/mandiant/flare-fakenet-ng/blob/ac33a706274d3e567080d261f7886fd472378ffa/fakenet/listeners/ProxyListener.py#L131) and [L335](https://github.com/mandiant/flare-fakenet-ng/blob/ac33a706274d3e567080d261f7886fd472378ffa/fakenet/listeners/ProxyListener.py#L335) should be changed to `sys.exit(1)`

Thanks to Conor Quigley for reporting this!

**Comment by 0xsys** [comment]
Hi, I would love to be assigned to this bug fix.

This would be my first contribution to the Open Source community.

Regards, 
0xsys

**Comment by tinajn** [comment]
@0xsys I have assigned it to you. Welcome to the community :)

**Comment by 0xsys** [comment]
Thanks for the warm welcome @tinajn !

Please let me know if I need to do anything else.
