### ISSUE TITLE
Look for configuration files in the binary location (vs the current directory)

### ISSUE THREAD

**Issue by Ana06** [mandiant/flare-fakenet-ng#180]
The `fakenet.exe` binary looks for the config files/folders in the current directory (the location from which is executed). This breaks the executable if executed from a location that is not where the binary resides in memory:
```
C:\Users\flare\Desktop > C:\Tools\fakenet\fakenet3.2-alpha\fakenet.exe

  ______      _  ________ _   _ ______ _______     _   _  _____
 |  ____/\   | |/ /  ____| \ | |  ____|__   __|   | \ | |/ ____|
 | |__ /  \  | ' /| |__  |  \| | |__     | |______|  \| | |  __
 |  __/ /\ \ |  < |  __| | . ` |  __|    | |______| . ` | | |_ |
 | | / ____ \| . \| |____| |\  | |____   | |      | |\  | |__| |
 |_|/_/    \_\_|\_\______|_| \_|______|  |_|      |_| \_|\_____|

                        Version 3.2
  _____________________________________________________________
                   Developed by FLARE Team
    Copyright (C) 2016-2024 Mandiant, Inc. All rights reserved.
  _____________________________________________________________

04/12/24 02:26:37 PM [           FakeNet] Could not open configuration file C:\Users\flare\Desktop\configs\default.ini
```

Would it be possible to change it to look for the config files in the location of the binary? It would make it nicer for user to use fakenet and also simplify FLARE-VM installation code as this is not standard case and we can't use the helper functions we use to install most tools.

**Comment by Ana06** [comment]
Reference: https://github.com/mandiant/VM-Packages/pull/989/files#diff-f4f88ea48ed378986c00cc2fa65f87f437b3754ed8c5111b80dd4cccb8c56450R6

**Comment by tinajohnson** [comment]
Resolved with https://github.com/mandiant/flare-fakenet-ng/pull/192. Thank you @emtuls and @Donaldduck8 for your contributions.
